feat(stacks): Add trigger disabled attribute to StackVCSRepo
hashicorp/go-tfe pull request #1017
Opened 2024-12-05 21:14 UTC by mjyocca

## Description

## Testing plan

## External links

## Output from tests
Including output from tests may require access to a TFE instance. Ignore this section if you have no environment to test against.

```
$ TFE_ADDRESS="https://example" TFE_TOKEN="example" go test ./... -v -run TestFunctionsAffectedByChange

...
```

2025-04-02 08:32 UTC, matejrisek approved these changes, later dismissed

2025-12-02 20:15 UTC, ctrombley requested changes

2025-12-02 20:15 UTC, ctrombley commented on stack.go
> +	TriggerDisabled   bool   `jsonapi:"attr,trigger-disabled"`
Would you mind adding an assertion (maybe to `TestStackReadUpdateDelete`) that validates this is being unmarshalled properly?

2026-06-15 22:01 UTC, brandonc commented
If this is still needed please modify the OpenAPI spec in the HCP Terraform platform code.

2026-06-15 22:01 UTC, closed without merging