Allow access to JSON version of state, and allow access to output variables that aren't strings
hashicorp/go-tfe pull request #161
Opened 2021-01-12 01:00 UTC by sfc-gh-ahess

This PR represents two changes to the go-tfe library:
1. It provides a method for retrieving the JSON state of a workspace
2. It provides a mechanism for accessing state outputs that are not strings.  The built-in StateVersionOutputs assumes all outputs are strings, and panics when an array or other non-string output is encountered, which Terraform does support.

2021-01-12 01:00 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/go-tfe?pullRequest=161)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/go-tfe?pullRequest=161)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/go-tfe?pullRequest=161).</sub>

2021-01-14 02:18 UTC, chrisarcand requested changes
Hello, and thanks for looking at this!

This PR includes two very unrelated features; for the sake of review and historical context, could you please split off one of these to a separate pull request? Thanks.

---

Reviewing the state version output part only: The existing behavior should never have been done that way and this can be considered a bug; your additional `ReadSimpler()` needn't be added in an attempt to keep backwards compatibility. I believe `StateVersionOutput.Value` should implement [the Unmarshaler interface](https://golang.org/pkg/encoding/json/#Unmarshaler) and properly allow for more types than just strings, using a normal `Read()` call.

2021-01-14 16:51 UTC, sfc-gh-ahess commented
Going to create a two new PRs to separate these issues.

2021-01-14 16:51 UTC, closed without merging

2021-01-14 17:08 UTC, sfc-gh-ahess commented
> Reviewing the state version output part only: The existing behavior should never have been done that way and this can be considered a bug; your additional `ReadSimpler()` needn't be added in an attempt to keep backwards compatibility. I believe `StateVersionOutput.Value` should implement [the Unmarshaler interface](https://golang.org/pkg/encoding/json/#Unmarshaler) and properly allow for more types than just strings, using a normal `Read()` call.

@chrisarcand : I feel like this is beyond the scope of a minor bugfix for me to make -- the unmarshaler interface would solve the retrieving of the data, but does not solve the issue of where to store it.  Does 'Value' remain an 'interface{}' ? Or do we create several value fields for every possible output type?  ValueInt? ValueString? ValueArray?

I think I will implement the latter to keep with strong typing.