Adds description to TFE Workspaces
hashicorp/go-tfe pull request #171
Opened 2021-02-05 15:40 UTC by petems

## Description

Adds description attribute to workspaces

## External links

https://www.terraform.io/docs/cloud/api/workspaces.html#request-body

2021-02-07 00:32 UTC, chrisarcand requested changes
Thanks, Peter! Just a few bits to wrap up and this looks good to me.

* `TestWorkspaceCreate` needs a line added to ensure the value you set ("bar") was set and is read properly back again. (see further along in the spec)
* A description can be updated - so a field for `WorkspaceUpdateOptions` is also necessary (along with, of course, some additions to that test as well).

2021-02-08 10:47 UTC, petems commented on workspace.go
> +	Description *string `jsonapi:"attr,description,omitempty"`
@chrisarcand Addded to WorkspaceUpdateOptions as requested 👍

2021-02-08 10:48 UTC, petems commented on workspace_test.go
> +			Description:         String("updated description"),
@chrisarcand Test for WorkspaceUpdate and checking value of description done!

2021-02-08 10:55 UTC, petems commented
@chrisarcand Done!

PS. Random thought, but it'd be nice if this used either mocks or something like go-vcr to run the tests, it's a bit of a pain having to setup TFE creds to run testing. Added as a GH issue for the future 🦖

2021-02-09 22:42 UTC, chrisarcand approved these changes

2021-02-09 22:42 UTC, merged

2021-02-16 15:32 UTC, petems commented
@chrisarcand Are you ok to tag a release now this has been merged?

2021-02-16 16:05 UTC, chrisarcand commented
[Released in v0.12.1](https://github.com/hashicorp/go-tfe/releases/tag/v0.12.1)