Admin Users API
hashicorp/go-tfe pull request #189
Opened 2021-03-10 18:09 UTC by omarismail

## Description

This PR adds all the [Admin Users API](https://www.terraform.io/docs/cloud/api/admin/users.html).

It implements: 
```
type AdminUsers interface {
	// List all the users of the given installation.
	List(ctx context.Context, options AdminUserListOptions) (*AdminUserList, error)

	// Delete a user by its ID.
	Delete(ctx context.Context, userID string) error

	// Suspend a user account by its ID.
	Suspend(ctx context.Context, userID string) (*AdminUser, error)

	// Unsuspend a user account by its ID.
	Unsuspend(ctx context.Context, userID string) (*AdminUser, error)

	// GrantAdminPrivlages to a user account by its ID.
	GrantAdminPrivlages(ctx context.Context, userID string) (*AdminUser, error)

	// RevokeAdminPrivlages to a user account by its ID.
	RevokeAdminPrivlages(ctx context.Context, userID string) (*AdminUser, error)

	// Disable2FA disables a user's two-factor authentication in the situation
	// where they have lost access to their device and recovery codes.
	Disable2FA(ctx context.Context, userID string) (*AdminUser, error)

	// ImpersonateUser allows an admin to begin a new session as another user in
	// the system
	ImpersonateUser(ctx context.Context, userID string, options ImpersonateReasonOption) error

	// UnimpersonateUser allows an admin to end an impersonationn session of
	// another user in the system
	UnimpersonateUser(ctx context.Context, userID string) error
}
```

## Testing plan

1. Pull down and run the tests 

## Output from tests

```
$ TFE_TOKEN=<token> TFE_ADDRESS=<address>  ENABLE_TFE=1 go test -v ./...  -timeout=30m
...
PASS
ok  	github.com/hashicorp/go-tfe	510.513s
?   	github.com/hashicorp/go-tfe/examples/organizations	[no test files]
?   	github.com/hashicorp/go-tfe/examples/workspaces	[no test files]
```

## External links

- [API documentation](https://www.terraform.io/docs/cloud/api/admin/users.html)

2021-03-16 05:00 UTC, chrisarcand requested changes
Nice!

2021-03-16 12:49 UTC, omarismail commented on admin_user.go
> +	GrantAdminPrivlages(ctx context.Context, userID string) (*AdminUser, error)
Sounds good

2021-03-16 12:57 UTC, omarismail commented on admin_user.go
> +	UnimpersonateUser(ctx context.Context, userID string) error
Yeeaahh, I was iffy on this one. It didn't make sense in the API but it was there, so figure'd i'd add it. 

I actually failed the read the entire doc area 🤦‍♂️ . 

I read the blue highlighted area and thought it was workable via the API, even though when I tested it it seemed to work under certain user conditions. But I didn't read the "Important" yellow area.

Will remove

![image](https://user-images.githubusercontent.com/4130121/111312307-881e2e00-8635-11eb-9587-eb8caab1d54a.png)

2021-03-16 13:05 UTC, omarismail commented on admin_user.go
> +	UnimpersonateUser(ctx context.Context, userID string) error
Updated

2021-03-16 15:32 UTC, chrisarcand requested changes

2021-03-16 15:32 UTC, chrisarcand commented on admin_user.go
> +	// RevokeAdmin revokees admin privlages to a user by its ID.
😜 

```suggestion
	// RevokeAdmin revokees admin privilages to a user by its ID.
```

2021-03-16 15:32 UTC, chrisarcand commented on admin_user.go
> +// RevokeAdmin revokes admin privlages to a user by its ID.
```suggestion
// RevokeAdmin revokes admin privilages to a user by its ID.
```

2021-03-16 15:32 UTC, chrisarcand commented on admin_user_test.go
> +func TestAdminUsers_AdminPrivlages_Suspensions(t *testing.T) {
```suggestion
func TestAdminUsers_AdminPrivilages_Suspensions(t *testing.T) {
```

2021-03-16 17:48 UTC, omarismail commented on admin_user.go
> +// RevokeAdmin revokes admin privlages to a user by its ID.
Clearly I can't spell

2021-03-17 15:28 UTC, chrisarcand approved these changes
Looks great! Nice work! 🚢

2021-03-17 15:48 UTC, merged