Enable workspace drift detection setting management
hashicorp/go-tfe pull request #462
Opened 2022-07-12 16:46 UTC by rexredinger

## Description

Allow go-tfe to access and manage drift detection setting for workspaces in TFC.

## Testing plan

## External links

- [API documentation](https://www.terraform.io/cloud-docs/api-docs/workspaces#request-body)
- tfe provider PR forthcoming.

## Output from tests
Including output from tests may require access to a TFE instance. Ignore this section if you have no environment to test against.

```
$ go test -run TestWorkspacesUpdate -v ./... -tags=integration
=== RUN   TestWorkspacesUpdate
=== RUN   TestWorkspacesUpdate/when_updating_a_subset_of_values
=== RUN   TestWorkspacesUpdate/with_valid_options
=== RUN   TestWorkspacesUpdate/when_options_includes_both_an_operations_value_and_an_enforcement_mode_value
=== RUN   TestWorkspacesUpdate/when_'agent'_execution_mode_is_specified_without_an_an_agent_pool_ID
=== RUN   TestWorkspacesUpdate/when_an_error_is_returned_from_the_api
=== RUN   TestWorkspacesUpdate/when_options_has_an_invalid_name
=== RUN   TestWorkspacesUpdate/when_options_has_an_invalid_organization
=== RUN   TestWorkspacesUpdate/when_options_include_trigger-patterns_(behind_a_feature_flag)
=== RUN   TestWorkspacesUpdate/when_options_include_both_trigger-patterns_and_trigger-paths_error_is_returned
=== RUN   TestWorkspacesUpdate/when_options_include_trigger-patterns_populated_and_empty_trigger-paths_workspace_is_updated
=== RUN   TestWorkspacesUpdate/when_options_include_VCSRepo_tags-regex_(behind_a_feature_flag)
    helper_test.go:1770: Skipping test related to a Terraform Cloud beta feature. Set ENABLE_BETA=1 to run.
=== RUN   TestWorkspacesUpdate/when_options_include_tags-regex_and_file-triggers-enabled_is_true_an_error_is_returned
=== RUN   TestWorkspacesUpdate/when_options_include_both_tags-regex_and_trigger-prefixes_an_error_is_returned
=== RUN   TestWorkspacesUpdate/when_options_include_both_tags-regex_and_trigger-patterns_error_is_returned
--- PASS: TestWorkspacesUpdate (4.31s)
    --- PASS: TestWorkspacesUpdate/when_updating_a_subset_of_values (0.17s)
    --- PASS: TestWorkspacesUpdate/with_valid_options (0.33s)
    --- PASS: TestWorkspacesUpdate/when_options_includes_both_an_operations_value_and_an_enforcement_mode_value (0.00s)
    --- PASS: TestWorkspacesUpdate/when_'agent'_execution_mode_is_specified_without_an_an_agent_pool_ID (0.00s)
    --- PASS: TestWorkspacesUpdate/when_an_error_is_returned_from_the_api (0.12s)
    --- PASS: TestWorkspacesUpdate/when_options_has_an_invalid_name (0.00s)
    --- PASS: TestWorkspacesUpdate/when_options_has_an_invalid_organization (0.00s)
    --- PASS: TestWorkspacesUpdate/when_options_include_trigger-patterns_(behind_a_feature_flag) (1.12s)
    --- PASS: TestWorkspacesUpdate/when_options_include_both_trigger-patterns_and_trigger-paths_error_is_returned (0.00s)
    --- PASS: TestWorkspacesUpdate/when_options_include_trigger-patterns_populated_and_empty_trigger-paths_workspace_is_updated (1.05s)
    --- SKIP: TestWorkspacesUpdate/when_options_include_VCSRepo_tags-regex_(behind_a_feature_flag) (0.00s)
    --- PASS: TestWorkspacesUpdate/when_options_include_tags-regex_and_file-triggers-enabled_is_true_an_error_is_returned (0.00s)
    --- PASS: TestWorkspacesUpdate/when_options_include_both_tags-regex_and_trigger-prefixes_an_error_is_returned (0.00s)
    --- PASS: TestWorkspacesUpdate/when_options_include_both_tags-regex_and_trigger-patterns_error_is_returned (0.00s)
=== RUN   TestWorkspacesUpdateByID
=== RUN   TestWorkspacesUpdateByID/when_updating_a_subset_of_values
=== RUN   TestWorkspacesUpdateByID/with_valid_options
=== RUN   TestWorkspacesUpdateByID/when_an_error_is_returned_from_the_api
=== RUN   TestWorkspacesUpdateByID/without_a_valid_workspace_ID
--- PASS: TestWorkspacesUpdateByID (1.46s)
    --- PASS: TestWorkspacesUpdateByID/when_updating_a_subset_of_values (0.14s)
    --- PASS: TestWorkspacesUpdateByID/with_valid_options (0.32s)
    --- PASS: TestWorkspacesUpdateByID/when_an_error_is_returned_from_the_api (0.11s)
    --- PASS: TestWorkspacesUpdateByID/without_a_valid_workspace_ID (0.00s)
PASS
ok  	github.com/hashicorp/go-tfe	6.533s
?   	github.com/hashicorp/go-tfe/examples/organizations	[no test files]
?   	github.com/hashicorp/go-tfe/examples/workspaces	[no test files]
?   	github.com/hashicorp/go-tfe/mocks	[no test files]
```

```
$ go test -run TestWorkspacesRead -v ./... -tags=integration
=== RUN   TestWorkspacesRead
=== RUN   TestWorkspacesRead/when_the_workspace_exists
=== RUN   TestWorkspacesRead/when_the_workspace_does_not_exist
=== RUN   TestWorkspacesRead/when_the_organization_does_not_exist
=== RUN   TestWorkspacesRead/without_a_valid_organization
=== RUN   TestWorkspacesRead/without_a_valid_workspace
--- PASS: TestWorkspacesRead (1.35s)
    --- PASS: TestWorkspacesRead/when_the_workspace_exists (0.13s)
    --- PASS: TestWorkspacesRead/when_the_workspace_does_not_exist (0.08s)
    --- PASS: TestWorkspacesRead/when_the_organization_does_not_exist (0.08s)
    --- PASS: TestWorkspacesRead/without_a_valid_organization (0.00s)
    --- PASS: TestWorkspacesRead/without_a_valid_workspace (0.00s)
=== RUN   TestWorkspacesReadWithOptions
=== RUN   TestWorkspacesReadWithOptions/when_options_to_include_resource
--- PASS: TestWorkspacesReadWithOptions (4.62s)
    --- PASS: TestWorkspacesReadWithOptions/when_options_to_include_resource (0.65s)
PASS
ok  	github.com/hashicorp/go-tfe	5.974s
?   	github.com/hashicorp/go-tfe/examples/organizations	[no test files]
?   	github.com/hashicorp/go-tfe/examples/workspaces	[no test files]
?   	github.com/hashicorp/go-tfe/mocks	[no test files]
```

```
$ go test -run TestWorkspacesCreate -v ./... -tags=integration
=== RUN   TestWorkspacesCreate
=== RUN   TestWorkspacesCreate/with_valid_options
=== RUN   TestWorkspacesCreate/when_options_is_missing_name
=== RUN   TestWorkspacesCreate/when_options_has_an_invalid_name
=== RUN   TestWorkspacesCreate/when_options_has_an_invalid_organization
=== RUN   TestWorkspacesCreate/when_options_includes_both_an_operations_value_and_an_enforcement_mode_value
=== RUN   TestWorkspacesCreate/when_an_agent_pool_ID_is_specified_without_'agent'_execution_mode
=== RUN   TestWorkspacesCreate/when_'agent'_execution_mode_is_specified_without_an_an_agent_pool_ID
=== RUN   TestWorkspacesCreate/when_an_error_is_returned_from_the_API
=== RUN   TestWorkspacesCreate/when_options_include_trigger-patterns_(behind_a_feature_flag)
=== RUN   TestWorkspacesCreate/when_options_include_both_non-empty_trigger-patterns_and_trigger-paths_error_is_returned
=== RUN   TestWorkspacesCreate/when_options_include_tags-regex(behind_a_feature_flag)
    helper_test.go:1770: Skipping test related to a Terraform Cloud beta feature. Set ENABLE_BETA=1 to run.
=== RUN   TestWorkspacesCreate/when_options_include_both_non-empty_tags-regex_and_trigger-patterns_error_is_returned
=== RUN   TestWorkspacesCreate/when_options_include_both_non-empty_tags-regex_and_trigger-prefixes_error_is_returned
=== RUN   TestWorkspacesCreate/when_options_include_both_non-empty_tags-regex_and_file-triggers-enabled_as_true_an_error_is_returned
=== RUN   TestWorkspacesCreate/when_options_include_trigger-patterns_populated_and_empty_trigger-paths_workspace_is_created
--- PASS: TestWorkspacesCreate (3.93s)
    --- PASS: TestWorkspacesCreate/with_valid_options (0.41s)
    --- PASS: TestWorkspacesCreate/when_options_is_missing_name (0.00s)
    --- PASS: TestWorkspacesCreate/when_options_has_an_invalid_name (0.00s)
    --- PASS: TestWorkspacesCreate/when_options_has_an_invalid_organization (0.00s)
    --- PASS: TestWorkspacesCreate/when_options_includes_both_an_operations_value_and_an_enforcement_mode_value (0.00s)
    --- PASS: TestWorkspacesCreate/when_an_agent_pool_ID_is_specified_without_'agent'_execution_mode (0.00s)
    --- PASS: TestWorkspacesCreate/when_'agent'_execution_mode_is_specified_without_an_an_agent_pool_ID (0.00s)
    --- PASS: TestWorkspacesCreate/when_an_error_is_returned_from_the_API (0.11s)
    --- PASS: TestWorkspacesCreate/when_options_include_trigger-p [...]

2022-07-20 17:45 UTC, annawinkler commented on workspace.go
> +	// Optional: Whether to enabled drift detection for the workspace.
```suggestion
	// Optional: Whether to enable drift detection for the workspace.
```

2022-07-20 17:46 UTC, annawinkler commented on workspace.go
> +	// Optional: Whether to enabled drift detection for the workspace.
```suggestion
	// Optional: Whether to enable drift detection for the workspace.
```

2022-07-20 18:20 UTC, annawinkler commented on workspace.go
> +	DriftDetection *bool `jsonapi:"attr,drift-detection,omitempty"`
It looks like the attributes are listed in alphabetical order (after the type). Could you move this new attribute to maintain that ordering?

2022-07-20 18:20 UTC, annawinkler commented on workspace.go
> +	DriftDetection *bool `jsonapi:"attr,drift-detection,omitempty"`
Same suggestion here regarding ordering of the attributes.

2022-07-20 18:22 UTC, annawinkler requested changes
Thanks for the PR! Could you also include a Changelog update?

2022-08-13 04:00 UTC, elijah-roberts commented
Super interested in this feature. @annawinkler is there anything else that needs to be added to get this PR merged?

Are you waiting for the tests to run successfully? @rexredinger  any thoughts on these? Not sure if it is a flaky test, or an actual config error.

2022-09-09 21:17 UTC, annawinkler commented on CHANGELOG.md
> +* Add support for managing workspace drift detection setting [#462](https://github.com/hashicorp/go-tfe/pull/462)
It looks like this PR adds support for enforcing assessments in an organization and workspace. Could you update the changelog entry to reflect that?

2022-09-09 21:20 UTC, annawinkler commented on organization.go
> +	// Optional: AssessmentsEnforced toggles whether health assessment enablement is enforced across all assessable workspaces or if the decission to enabled health assessments is delegated to the works
```suggestion
	// Optional: AssessmentsEnforced toggles whether health assessment enablement is enforced across all assessable workspaces or if the decision to enabled health assessments is delegated to the workspace setting AssessmentsEnabled.
```

Could you clarify what an assessable workspace is?

2022-09-09 21:21 UTC, annawinkler commented on organization.go
> +	// Optional: AssessmentsEnforced toggles whether health assessment enablement is enforced across all assessable workspaces or if the decission to enabled health assessments is delegated to the works
```suggestion
	// Optional: AssessmentsEnforced toggles whether health assessment enablement is enforced across all assessable workspaces or if the decision to enabled health assessments is delegated to the workspace setting AssessmentsEnabled.
```

2022-09-09 22:25 UTC, annawinkler requested changes
🥇 This is looking really good! I have a few small suggestions and then I think this PR will be ready to go after we've merged & built go-tfe with that PR.

2022-09-12 19:03 UTC, annawinkler commented on workspace_integration_test.go
>  	t.Run("when updating a subset of values", func(t *testing.T) {
We'll need to upgrade the organization for this test to pass, so adding something like this:

```
upgradeOrganizationSubscription(t, client, orgTest)
```

On or around line 670 would work.

2022-09-12 20:17 UTC, rexredinger commented
Updated workspace test with the `upgradeOrganizationSubscription`
and got this happy result in staging.
```
go test -run TestWorkspacesUpdate/when_updating_a_subset_of_values -v ./... -tags=integration
=== RUN   TestWorkspacesUpdate
=== RUN   TestWorkspacesUpdate/when_updating_a_subset_of_values
--- PASS: TestWorkspacesUpdate (1.39s)
    --- PASS: TestWorkspacesUpdate/when_updating_a_subset_of_values (0.18s)
=== RUN   TestWorkspacesUpdateByID
=== RUN   TestWorkspacesUpdateByID/when_updating_a_subset_of_values
--- PASS: TestWorkspacesUpdateByID (1.02s)
    --- PASS: TestWorkspacesUpdateByID/when_updating_a_subset_of_values (0.15s)
PASS
ok  	github.com/hashicorp/go-tfe	2.671s
?   	github.com/hashicorp/go-tfe/examples/organizations	[no test files]
?   	github.com/hashicorp/go-tfe/examples/workspaces	[no test files]
?   	github.com/hashicorp/go-tfe/mocks	[no test files]
```

2022-09-13 21:37 UTC, annawinkler commented on organization.go
> +	AssessmentsEnforced                               bool                     `jsonapi:"attr,assessments-enforced"`
💅 Could you add this attribute in alphabetical order?

2022-09-13 21:38 UTC, annawinkler commented on workspace.go
> +	AssessmentsEnabled         bool                  `jsonapi:"attr,assessments-enabled"`
💅 Could you add this attribute in alphabetical order?

2022-09-14 20:59 UTC, annawinkler approved these changes
🔥 🍪

2022-09-14 22:03 UTC, annawinkler approved these changes
:shipit:

2022-09-14 22:10 UTC, merged