[DO NOT MERGE] Changes to Policy set API for PPRV
hashicorp/go-tfe pull request #752
Opened 2023-08-11 01:54 UTC by mrinalirao

## Description

## Testing plan

## External links

## Output from tests
Including output from tests may require access to a TFE instance. Ignore this section if you have no environment to test against.

```
$ TFE_ADDRESS="https://example" TFE_TOKEN="example" go test ./... -v -run TestFunctionsAffectedByChange

...
```

2024-01-23 00:01 UTC, nfagerlund requested changes
I haven't fully reviewed the code yet, but there was one glaring problem (in multiple places) that jumped out at me, and I wanted to send it back to you as soon as I could. I'll take another look once you've got that sorted out!

2024-01-23 10:46 UTC, mrinalirao commented on policy_set.go
> +	PolicyToolVersion string `jsonapi:"attr,policy-tool-version,omitempty"`
Thanks for catching that !!👍 Pushed the suggested fix. :)

2024-01-24 02:02 UTC, nfagerlund requested changes
Ok, this is mostly looking good, other than one missing omitempty. My only other real concern at this point is making sure the doc comments are easy to understand. Comments inline.

2024-01-24 02:02 UTC, nfagerlund commented on policy_set.go
> +	PolicyToolVersion *string `jsonapi:"attr,policy-tool-version"`
This is still missing an `,omitempty`.

2024-01-24 03:02 UTC, mrinalirao commented on policy_set_integration_test.go
> +		DeprecatedReason: String("Test Reason"),
fixed 😅

2024-01-24 03:03 UTC, mrinalirao commented on policy_set.go
> +	// Optional: Whether or not users can override this policy when it fails during a run. Only valid for policy evaluations.
yes, policy evaluations are very different from policy checks in the way they ate executed (agent vs sentinel worker), i have added a link to the docs in the comment.

2024-01-24 22:47 UTC, nfagerlund approved these changes

2024-01-24 22:50 UTC, merged