[TF-10829] add new organization setting option
hashicorp/go-tfe pull request #829
Opened 2023-12-11 22:38 UTC by mjyocca

## Description

## Testing plan

## External links

## Output from tests
Including output from tests may require access to a TFE instance. Ignore this section if you have no environment to test against.

```
$ TFE_ADDRESS="https://example" TFE_TOKEN="example" go test ./... -v -run TestFunctionsAffectedByChange

...
```

2024-01-17 18:37 UTC, brandonc approved these changes

2024-01-17 18:37 UTC, brandonc commented on organization.go
> +	AggregatedCommitStatusEnabled bool `jsonapi:"attr,aggregated-commit-status-enabled,omitempty"`
No need for omitempty here, since `false` would be given either way.

2024-01-17 19:25 UTC, brandonc requested changes

2024-01-17 19:25 UTC, brandonc commented on organization.go
> +	AggregatedCommitStatusEnabled *bool `jsonapi:"attr,aggregated-commit-status-enabled"`
Oh, these Update/Create options should continue to be omitempty, because in this case the empty pointer omits the attribute!

2024-01-17 19:41 UTC, brandonc approved these changes

2024-01-17 20:19 UTC, lilincmu submitted a review, later dismissed
Looks good to me!

2024-01-18 19:26 UTC, lilincmu approved these changes

2024-01-18 19:32 UTC, brandonc approved these changes

2024-01-18 19:33 UTC, merged