TF-20627: Add Waypoint entitlements for organizations
hashicorp/go-tfe pull request #984
Opened 2024-09-30 17:41 UTC by ignatius-j

## Description

These changes add to the organizational entitlement struct to be able to
utilize the new Waypoint-based entitlements granted with HCP Terraform
feature sets:

- waypoint-actions
- waypoint-templates-and-addons

## Testing plan

## External links

- [Jira](https://hashicorp.atlassian.net/browse/TF-20627)
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/xxxx)
- [Related PR](https://github.com/hashicorp/atlas/pull/21086)

## Output from tests
Including output from tests may require access to a TFE instance. Ignore this section if you have no environment to test against.

```
$ TFE_ADDRESS="https://example" TFE_TOKEN="example" go test ./... -v -run TestFunctionsAffectedByChange

...
```

2024-09-30 18:53 UTC, sebasslash requested changes
It looks like our CI instance does not support these entitlements; or we need an organization with the `Plus` feature set, which to my knowledge can't be upgraded via the feature set API. In the meantime could you put these assertions under a new subtest `t.Run("with HCP entitlements", func(t *testing.T) {})` and subsequently skip the substep with a [skipUnlessAfterDate()](https://github.com/hashicorp/go-tfe/blob/f3328dacb7fffee955b2e3b371ae7e8984ecb1a4/helper_test.go#L2797) until we investigate this. If you can also paste the test results from your own local testing that would be great :heart:

2024-09-30 18:54 UTC, sebasslash commented
Let's also add a changelog entry, please :pray:

2024-10-01 20:06 UTC, sebasslash commented on organization_integration_test.go
> +	defer orgTestCleanup()
Generally I always prefer `t.Cleanup()` for tests, but in this scenario either is fine.

2024-10-01 20:19 UTC, brandonc commented on organization_integration_test.go
> +	defer orgTestCleanup()
t.Cleanup works better in two situations: using `t.Run()` (they clean up after the Test function finishes), and after panics

2024-10-01 20:27 UTC, brandonc commented on organization_integration_test.go
> +	defer orgTestCleanup()
(so we should just use it all the time)

2024-10-01 20:30 UTC, sebasslash approved these changes
The tests are passing:
```
PASS TestOrganizationsReadEntitlements/when_the_org_exists (0.09s)
PASS TestOrganizationsReadEntitlements/with_invalid_name (0.00s)
PASS TestOrganizationsReadEntitlements/when_the_org_does_not_exist (0.08s)
```

2024-10-01 20:30 UTC, sebasslash commented on subscription_updater_test.go
> +}
:heart:

2024-10-01 20:40 UTC, merged